# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NeoNkOUeGXV1oW2ZUWzWXdib1NErIB07

Data types

1)number
2)String
3)Boolean
"""

a = 10
b = 101.22
c = 'hello'
d = '''
  multi line string
  hello
  my 
  name
  is shashi
'''

print(a)
print(b)
print(c)
print(d)

# single line comment
'''
  multi line comments
  hello
  my 
  name
  is shashi
'''

"""Strings"""

string1 = "hello"
string2 = 'hello'
string3 = '''hello'''
print(string1)
print(string2)
print(string3)

# string slicing
print('positive indexing :')
print(string1[0])
print(string1[2])
print(string1[0:4])
print(string1[0:])
print(string1[:3])
print("negative indexing :")
print(string1[:])
print(string1[-1])
print(string1[-3:-1])
print("reverse :")
print(string1[::-1])
print("jumping :")
print(string1[0:5:2])
print(string1[-5:-1:2])

# [ start_position : end_position : jump/order ]

# concatination
new_string = string1 + string2
print(new_string)

# printing escape sequences
string = "c:shashi\name"
print(string)
string = "c:shashi\\name"
print(string)
string = r'c:shashi\name'
print(string)

# multiplication of string with a number
string_mul = string1*2 + ' humma'
print(string_mul)

"""List"""

a = [10,15.2,"hello"]
b = [15,15.9,"hai"]

print(a)
print(b)

# concatination
output = a + b
print(output)

# slicing is also applicable
print(a[0])
print(b[::-1])
print(output[::2])

# updating
a[0] = "baby"
print(a)

# adding new elements
a.append("shashi")
print(a)

# replacing
a[0:2] = ["sai", 'dinnu', "amma"]
print(a)

# clearing a list
a[:] = []
print(a)

# length of list
print(len(output))

"""Tuple"""

tuple1 = ("hello", 100, 50.9)
print(tuple1)

# the tuple is unmutable
# slicing is possible
print(tuple1[0])
# negative indexing is also possible

"""Dictionary"""

# dict1 = {keys : values}
# keys must be unmutale
dict1 = {'hello' : 1, 'hai' : 2}
print(dict1)

# elements of a dictionary is accessed using index
print(dict1['hello'])

# updating
dict1['hello'] = 5

# adding
dict1['buddy'] = 6
print(dict1)

